### PR TITLE
feat: updated frontend-build & frontend-platform major versions

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Description**
Major version upgrades, Updating `frontend-build` to v14 & `frontend-platform` to v8 along with respective edx packages

[Reference to respective MFEs with the build and platform major version upgrades to be released as minor versions instead of major ](https://github.com/openedx/frontend-component-header/pull/369#discussion_r1574802668)

### CODE REVIEW

**Comment by jsnwesson** [comment]
Since the footer and header packages were removed in #61 , I think we can close this PR and make the version bumps to Build/Platform when needed.

**Comment by BilalQamar95** [comment]
@jsnwesson this was less about header & footer packages and more about frontend-build/platform major version upgrades which upgrades jest to v29. Since Jest v29 upgrade is being done across all MFEs, this is a required upgrade as this particular MFE is acting as a blocker for its consumers for the jest upgrade. I'm re-opening the PR, hopefully you can help get this approved and merged to unblock its consumers

**Comment by jsnwesson** [comment]
Apologies for prematurely closing this PR! I'll be looking at this tomorrow to make sure it works as expected. If you would be able to update the `package.json`s for each example app to use the new version of `frontend-build` (and running them locally to make sure the plugins still appear), that'll add confidence for me that this PR won't have any negative impact on the MFEs using plugins.

**Comment by BilalQamar95** [comment]
> Apologies for prematurely closing this PR! I'll be looking at this tomorrow to make sure it works as expected. If you would be able to update the `package.json`s for each example app to use the new version of `frontend-build` (and running them locally to make sure the plugins still appear), that'll add confidence for me that this PR won't have any negative impact on the MFEs using plugins.

Sure, I have updated `frontend-build` along with `header`/`footer` for example apps & ran them without any issues

**Review by jsnwesson — APPROVED** [review]

**Pull request merged**
